"""Ablation table (engine v3): finals and cumulative incumbent regret for
the paper's MinimalBench methods per condition. HQCBO uses hierarchy-only
refinement (archive key HQCBOGF). Reads artifacts/summaries/minimal_exact.json (run
summarize_minimal_exact.py first) and writes paper/tables/minimal_ablations.tex.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from scripts.publication_methods import publication_name, validate_summary

ARMS = ["BO", "BOS", "CBO", "CBONP", "QCBO", "QCBONP", "HQCBOGF"]
LABEL = {a: publication_name(a, latex=True) for a in ARMS}
ROWS = [("ParallelParent", "A0", "PP A0 (correct)", 50),
        ("ParallelParent", "A1", r"PP A1 (del $X_1{\to}Y$)", 50),
        ("ParallelParent", "A2", r"PP A2 (add $X_1{\to}X_2$)", 50),
        ("ParallelParent", "A3", r"PP A3 (assume $X_1\leftrightarrow Y$)", 50),
        ("FrontDoor", "B0", "FD B0 (correct)", 50),
        ("FrontDoor", "B1", r"FD B1 (assume $X_1\leftrightarrow M$)", 50),
        ("MediatedChain", "C0", "MC C0", 60)]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--summary", default="artifacts/summaries/minimal_exact.json")
    ap.add_argument("--out", default="paper/tables/minimal_ablations.tex")
    args = ap.parse_args()
    s = json.loads(Path(args.summary).read_text())
    g = s["groups"]
    validate_summary(g)

    lines = [r"\begin{tabular}{@{}llrr@{}}", r"\toprule",
             r"\textbf{Condition} & \textbf{Method} & \textbf{Final} & $R_T$ \\", r"\midrule"]
    for scm, cond, title, T in ROWS:
        first = True
        for arm in ARMS:
            key = f"{scm}_{cond}_{arm}"
            if arm == "HQCBOGF" and scm != "MediatedChain":
                continue
            r = g[key]
            lines.append(
                rf"{title if first else ''} & {LABEL[arm]} & "
                rf"${r['final_mean']:.4f}{{\scriptstyle\,\pm\,}}{r['final_se']:.4f}$ & "
                rf"${r['cumulative_regret_mean']:.2f}{{\scriptstyle\,\pm\,}}{r['cumulative_regret_se']:.2f}$ \\")
            first = False
        lines.append(r"\addlinespace[2pt]")
    lines += [r"\bottomrule", r"\end{tabular}"]
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("% Auto-generated by scripts/emit_minimal_ablation_table.py -- do not edit.\n"
                   + "\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
