"""Emit paper Table 1 (perturbation taxonomy) from ccbo.minibench.

The structural columns come straight from ``minibench.PERTURBATIONS`` so the
paper cannot drift from the code; the observed column is the sup-norm paired
invariance check over the suite CSVs when they exist:

    sup over seeds, trials |best_y(cond, seed, t) - best_y(A0, seed, t)|

for the QCBO arm (same seed, same trial — the paired-by-seed protocol).

Run:  PYTHONPATH=. python scripts/emit_minimal_taxonomy.py \
          [--dir results/minimal] [--out paper/tables/minimal_taxonomy.tex]
"""

import os
import sys
import glob
import argparse

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO not in sys.path:
    sys.path.insert(0, _REPO)

import numpy as np
import pandas as pd

from ccbo import minibench as mb


_BASELINE = {"A": "A0", "B": "B0", "C": "C0"}


def _sup_delta(results_dir, scm, cond):
    """sup_t,seed |QCBO(cond) - QCBO(baseline)| over paired seeds; None if
    no data. The baseline is the same-SCM correct condition."""
    base = _BASELINE[cond[0]]
    deltas = []
    for f0 in sorted(glob.glob(os.path.join(
            results_dir, f"{scm}_{base}_QCBO_seed*.csv"))):
        fc = f0.replace(f"_{base}_", f"_{cond}_")
        if not os.path.exists(fc):
            continue
        y0 = pd.read_csv(f0)["best_y"].to_numpy(float)
        yc = pd.read_csv(fc)["best_y"].to_numpy(float)
        n = min(len(y0), len(yc))
        deltas.append(np.abs(y0[:n] - yc[:n]).max())
    return max(deltas) if deltas else None


def _mark(flag):
    if flag is None:
        return "--"
    return r"\checkmark" if flag else r"$\times$"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default="results/minimal")
    ap.add_argument("--out", default="paper/tables/minimal_taxonomy.tex")
    args = ap.parse_args()

    lines = [
        "% AUTO-GENERATED by scripts/emit_minimal_taxonomy.py -- do not edit.",
        "% Structural columns come from ccbo/minibench.py PERTURBATIONS;",
        "% observed column is the sup-norm paired QCBO invariance check.",
        r"\begin{tabular}{@{}llcccr@{}}",
        r"\toprule",
        r"Cond. & Edit (assumed graph) & \begin{tabular}[c]{@{}c@{}}Quotient\\changed\end{tabular}"
        r" & \begin{tabular}[c]{@{}c@{}}Fine MIS\\changed\end{tabular}"
        r" & \begin{tabular}[c]{@{}c@{}}Fine prior\\changed\end{tabular}"
        r" & $\sup|\Delta|$ \\",
        r"\midrule",
    ]
    labels = {
        "A1": r"del $X_1\!\to\!Y$ (quotient-redundant)",
        "A2": r"add $X_1\!\to\!X_2$ (intra-cluster bow)",
        "A3": r"assume $X_1\!\leftrightarrow\!Y$ (quotient-visible)",
        "B1": r"assume $X_1\!\leftrightarrow\!M$ (intra-cluster conf.)",
    }
    scm_tag = {mb.PP_NAME: "PP", mb.FD_NAME: "FD"}
    for p in mb.PERTURBATIONS:
        if p["id"] not in labels:
            continue
        sup = _sup_delta(args.dir, str(p["scm"]), p["id"])
        obs = "--" if sup is None else (
            "0" if sup == 0.0 else f"{sup:.3g}")
        lines.append(
            f"{p['id']} ({scm_tag[p['scm']]}) & {labels[p['id']]} & "
            f"{_mark(p['quotient_changed'])} & "
            f"{_mark(p['fine_mis_changed'])} & "
            f"{_mark(p['fine_prior_changed'])} & {obs} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
